stages:
  - build
  - test
  - sonarqube
  - deploy

build:
  script:
    - "mvn clean install -DskipTests"
  stage: build

test:
  script:
    - "mvn test"
  stage: test

sonarqube:
  script:
    - "mvn verify sonar:sonar"
  stage: sonarqube

deploy:
  # Build Docker container and push to Docker Hub
  stage: deploy
  before_script:
    - "mvn clean install -DskipTests"
  script:
    - sh deploy.sh
  only:
    refs:
      - master

