version: "3"
services:
  invoice-creator-service:
    image: invoice-creator-service
    ports:
      - "9091:9090"
    networks:
      - mysql
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    networks:
      - mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=invoice_generator

networks:
  mysql: